aws:
  region: us-east-2

project:
  directory: packages
  babelConfig: >
    {
      "presets": [
        [
          "@babel/preset-env",
          {
            "targets": {
              "node": "12",
              "esmodules": true
            }
          }
        ]
      ],
        "plugins": [
        [
          "@babel/plugin-transform-runtime",
          {
            "corejs": 3
          }
        ]
      ]
    }
  lambda: >
    export async function :lambda_name(event) {
      console.log('Loading function', event);
    }
  lambdaTest: >
    import { :lambda_name } from '../src/handlers'

    describe('Given handler', () => {
      test('should expose the lambda function handler', () => {
        expect(typeof :lambda_name).toBe('function')
      })
    })
  projectPackageJson: >
    {
      "name": ":package_name",
      "version": "1.0.0",
      "description": "",
      "main": "app.js",
      "scripts": {
        "start": "node app.js",
        "test": "jest"
      },
      "keywords": [],
      "author": "",
      "license": "ISC"
    }
  lambdaPackageJson: >
    {
      "name": ":package_name",
      "version": "1.0.0",
      "description": "",
      "main": "app.js",
      "scripts": {
        "start": "node app.js",
        "test": "jest"
      },
      "keywords": [],
      "author": "",
      "license": "ISC"
    }
terraform:
  iam: >
    resource "aws_iam_role" ":lambda_name_role" {
      name = ":lambda_name_role"

      assume_role_policy = jsonencode({
        "Version" : "2012-10-17",
        "Statement" : [
          {
            "Effect" : "Allow",
            "Principal" : {
              "Service" : "lambda.amazonaws.com"
            },
            "Action" : "sts:AssumeRole"
          }
        ]
      })

    }
  lambda: >
    resource "aws_lambda_function" ":lambda_name" {
      filename      = ":package_name.zip"
      function_name = ":package_name"
      role          = aws_iam_role.:lambda_name_role.arn
      handler       = "dist/handlers.:package_name"

      source_code_hash = filebase64sha256("../packages/:package_name/function.zip")

      runtime = "nodejs12.x"
    }
  archive: >
    data "archive_file" ":lambda_name" {
      type = "zip"

      source_dir  = "${path.module}/:package_name"
      output_path = "${path.module}/:package_name.zip"
    }
  provider: >
    provider "aws" {
      region     = ":region"
      # access_key = ""
      # secret_key = ""
    }

monoJson: >
  {
    "packageDir": "packages",
    "componentDir": "components",
    "strictMode": true,
    "packages": {}
  }

gitignore: >
    # Logs
    logs
    *.log
    npm-debug.log*
    yarn-debug.log*
    yarn-error.log*
    lerna-debug.log*
    .pnpm-debug.log*

    # Diagnostic reports (https://nodejs.org/api/report.html)
    report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

    # Runtime data
    pids
    *.pid
    *.seed
    *.pid.lock

    # Directory for instrumented libs generated by jscoverage/JSCover
    lib-cov

    # Coverage directory used by tools like istanbul
    coverage
    *.lcov

    # nyc test coverage
    .nyc_output

    # Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
    .grunt

    # Bower dependency directory (https://bower.io/)
    bower_components

    # node-waf configuration
    .lock-wscript

    # Compiled binary addons (https://nodejs.org/api/addons.html)
    build/Release

    # Dependency directories
    node_modules/
    jspm_packages/

    # Snowpack dependency directory (https://snowpack.dev/)
    web_modules/

    # TypeScript cache
    *.tsbuildinfo

    # Optional npm cache directory
    .npm

    # Optional eslint cache
    .eslintcache

    # Optional stylelint cache
    .stylelintcache

    # Microbundle cache
    .rpt2_cache/
    .rts2_cache_cjs/
    .rts2_cache_es/
    .rts2_cache_umd/

    # Optional REPL history
    .node_repl_history

    # Output of 'npm pack'
    *.tgz

    # Yarn Integrity file
    .yarn-integrity

    # dotenv environment variables file
    .env.development.local
    .env.test.local
    .env.production.local
    .env.local

    # parcel-bundler cache (https://parceljs.org/)
    .cache
    .parcel-cache

    # Next.js build output
    .next
    out

    # Nuxt.js build / generate output
    .nuxt
    dist

    # Gatsby files
    .cache/
    # Comment in the public line in if your project uses Gatsby and not Next.js
    # https://nextjs.org/blog/next-9-1#public-directory-support
    # public

    # vuepress build output
    .vuepress/dist

    # vuepress v2.x temp and cache directory
    .temp
    .cache

    # Serverless directories
    .serverless/

    # FuseBox cache
    .fusebox/

    # DynamoDB Local files
    .dynamodb/

    # TernJS port file
    .tern-port

    # Stores VSCode versions used for testing VSCode extensions
    .vscode-test

    # yarn v2
    .yarn/cache
    .yarn/unplugged
    .yarn/build-state.yml
    .yarn/install-state.gz
    .pnp.*